// Generated by Wrangler by running `wrangler types`

interface Env {
	OPENAI_MODEL: "gpt-4o";
	AI_GATEWAY_NAME: "ask-cloudflare-mcp";
	GEMINI_MODEL: "gemini-2.5-flash";
	OPENAI_API_KEY: string;
	CLOUDFLARE_AI_GATEWAY_TOKEN: string;
	CLOUDFLARE_BROWSER_RENDER_TOKEN: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_IMAGES_TOKEN: string;
	GEMINI_API_KEY: string;
	OPENAI_AGENT: DurableObjectNamespace<import("./src/index").OpenAIAgent>;
	RESEARCH_AGENT: DurableObjectNamespace<import("./src/index").ResearchAgent>;
	DB: D1Database;
	AI: Ai;
}
